# Generated by Django 5.1.2 on 2024-10-27 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Engineering', 'Engineering'), ('Computer  Sciences', 'Computer  Sciences'), ('Medical', 'Medical'), ('Pharmacy', 'Pharmacy'), ('Dentistry', 'Dentistry')], max_length=50)),
                ('credit_hours', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=2)),
                ('parent_phoneNumber', models.CharField(max_length=11, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=2)),
                ('phoneNumber', models.CharField(max_length=11, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Geography', 'Geography'), ('History', 'History'), ('Arabic', 'Arabic'), ('English', 'English'), ('French', 'French')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
            },
        ),
    ]
